package in.kmbs.vlethyme.model;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "vlethyme")
public class Message implements java.io.Serializable {

	private Integer id;
	private Message message;
	private String from;
	private String subject;
	private String body;
	private Date createDate;
	private Integer userId;
	private Set<MessgeRecepient> messgeRecepients = new HashSet<MessgeRecepient>(0);
	private Set<Message> messages = new HashSet<Message>(0);

	public Message() {
	}

	public Message(Message message, String from, String subject, String body, Date createDate, Integer userId, Set<MessgeRecepient> messgeRecepients,
			Set<Message> messages) {
		this.message = message;
		this.from = from;
		this.subject = subject;
		this.body = body;
		this.createDate = createDate;
		this.userId = userId;
		this.messgeRecepients = messgeRecepients;
		this.messages = messages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentMessageId")
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@Column(name = "from", length = 45)
	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	@Column(name = "subject", length = 45)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "body", length = 65535)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	public Set<MessgeRecepient> getMessgeRecepients() {
		return this.messgeRecepients;
	}

	public void setMessgeRecepients(Set<MessgeRecepient> messgeRecepients) {
		this.messgeRecepients = messgeRecepients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
