package in.kmbs.vlethyme.model;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "vlethyme")
public class Resource implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean type;
	private Set<CourseResource> courseResources = new HashSet<CourseResource>(0);

	public Resource() {
	}

	public Resource(int id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<CourseResource> getCourseResources() {
		return this.courseResources;
	}

	public void setCourseResources(Set<CourseResource> courseResources) {
		this.courseResources = courseResources;
	}

}
