package in.kmbs.vlethyme.model;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name = "survey", catalog = "vlethyme")
public class Survey implements java.io.Serializable {

	private int id;
	private String title;
	private Integer userId;
	private String createDate;
	private Set<SurveyUser> surveyUsers = new HashSet<SurveyUser>(0);
	private Set<SurveyQuestion> surveyQuestions = new HashSet<SurveyQuestion>(0);
	private Set<SurveyOption> surveyOptions = new HashSet<SurveyOption>(0);

	public Survey() {
	}

	public Survey(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public Survey(int id, String title, Integer userId, String createDate, Set<SurveyUser> surveyUsers, Set<SurveyQuestion> surveyQuestions,
			Set<SurveyOption> surveyOptions) {
		this.id = id;
		this.title = title;
		this.userId = userId;
		this.createDate = createDate;
		this.surveyUsers = surveyUsers;
		this.surveyQuestions = surveyQuestions;
		this.surveyOptions = surveyOptions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "create_date", length = 45)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey")
	public Set<SurveyUser> getSurveyUsers() {
		return this.surveyUsers;
	}

	public void setSurveyUsers(Set<SurveyUser> surveyUsers) {
		this.surveyUsers = surveyUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey")
	public Set<SurveyQuestion> getSurveyQuestions() {
		return this.surveyQuestions;
	}

	public void setSurveyQuestions(Set<SurveyQuestion> surveyQuestions) {
		this.surveyQuestions = surveyQuestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey")
	public Set<SurveyOption> getSurveyOptions() {
		return this.surveyOptions;
	}

	public void setSurveyOptions(Set<SurveyOption> surveyOptions) {
		this.surveyOptions = surveyOptions;
	}

}
