package in.kmbs.vlethyme.entity;

// Generated Mar 25, 2014 5:04:32 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Forum generated by hbm2java
 */
@Entity
@Table(name = "forum")
public class Forum implements java.io.Serializable {

	private Integer id;
	private User user;
	private String title;
	private String content;
	private Date createDate;
	private String modifyDate;
	private List<ForumMember> forumMembers = new ArrayList<ForumMember>(0);
	private List<ForumPost> forumPosts = new ArrayList<ForumPost>(0);

	public Forum() {
	}

	public Forum(User user) {
		this.user = user;
	}

	public Forum(User user, String title, String content, Date createDate, String modifyDate, List<ForumMember> forumMembers, List<ForumPost> forumPosts) {
		this.user = user;
		this.title = title;
		this.content = content;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.forumMembers = forumMembers;
		this.forumPosts = forumPosts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "modify_date", length = 45)
	public String getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(String modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "forum")
	public List<ForumMember> getForumMembers() {
		return this.forumMembers;
	}

	public void setForumMembers(List<ForumMember> forumMembers) {
		this.forumMembers = forumMembers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "forum")
	public List<ForumPost> getForumPostses() {
		return this.forumPosts;
	}

	public void setForumPostses(List<ForumPost> forumPosts) {
		this.forumPosts = forumPosts;
	}

}
