package in.kmbs.vlethyme.entity;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GradeAssignment generated by hbm2java
 */
@Entity
@Table(name = "grade_assignment", catalog = "vlethyme")
public class GradeAssignment implements java.io.Serializable {

	private int id;
	private UserCourse userCourse;
	private Grade grade;
	private Assignment assignment;

	public GradeAssignment() {
	}

	public GradeAssignment(int id, UserCourse userCourse, Grade grade, Assignment assignment) {
		this.id = id;
		this.userCourse = userCourse;
		this.grade = grade;
		this.assignment = assignment;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userCourseId", nullable = false)
	public UserCourse getUserCourse() {
		return this.userCourse;
	}

	public void setUserCourse(UserCourse userCourse) {
		this.userCourse = userCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gradeId", nullable = false)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assignmentId", nullable = false)
	public Assignment getAssignment() {
		return this.assignment;
	}

	public void setAssignment(Assignment assignment) {
		this.assignment = assignment;
	}

}
