package in.kmbs.vlethyme.entity;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "vlethyme")
public class Grade implements java.io.Serializable {

	private int id;
	private char grade;
	private String description;
	private Set<GradeAssignment> gradeAssignments = new HashSet<GradeAssignment>(0);

	public Grade() {
	}

	public Grade(int id, char grade, String description) {
		this.id = id;
		this.grade = grade;
		this.description = description;
	}

	public Grade(int id, char grade, String description, Set<GradeAssignment> gradeAssignments) {
		this.id = id;
		this.grade = grade;
		this.description = description;
		this.gradeAssignments = gradeAssignments;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "grade", nullable = false, length = 1)
	public char getGrade() {
		return this.grade;
	}

	public void setGrade(char grade) {
		this.grade = grade;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<GradeAssignment> getGradeAssignments() {
		return this.gradeAssignments;
	}

	public void setGradeAssignments(Set<GradeAssignment> gradeAssignments) {
		this.gradeAssignments = gradeAssignments;
	}

}
