package in.kmbs.vlethyme.entity;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupUser generated by hbm2java
 */
@Entity
@Table(name = "group_user", catalog = "vlethyme")
public class GroupUser implements java.io.Serializable {

	private Integer id;
	private Role role;
	private Group group;
	private User user;
	private Set<SurveyUser> surveyUsers = new HashSet<SurveyUser>(0);

	public GroupUser() {
	}

	public GroupUser(Group group, User user) {
		this.group = group;
		this.user = user;
	}

	public GroupUser(Role role, Group group, User user, Set<SurveyUser> surveyUsers) {
		this.role = role;
		this.group = group;
		this.user = user;
		this.surveyUsers = surveyUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleId")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupId", nullable = false)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupUser")
	public Set<SurveyUser> getSurveyUsers() {
		return this.surveyUsers;
	}

	public void setSurveyUsers(Set<SurveyUser> surveyUsers) {
		this.surveyUsers = surveyUsers;
	}

}
