package in.kmbs.vlethyme.entity;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "vlethyme")
public class Module implements java.io.Serializable {

	private Integer id;
	private Course course;
	private String name;
	private Set<UserModule> userModules = new HashSet<UserModule>(0);
	private Set<Assignment> assignments = new HashSet<Assignment>(0);
	private Set<UserModule> userModules_1 = new HashSet<UserModule>(0);

	public Module() {
	}

	public Module(Course course, String name) {
		this.course = course;
		this.name = name;
	}

	public Module(Course course, String name, Set<UserModule> userModules, Set<Assignment> assignments, Set<UserModule> userModules_1) {
		this.course = course;
		this.name = name;
		this.userModules = userModules;
		this.assignments = assignments;
		this.userModules_1 = userModules_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<UserModule> getUserModules() {
		return this.userModules;
	}

	public void setUserModules(Set<UserModule> userModules) {
		this.userModules = userModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Assignment> getAssignments() {
		return this.assignments;
	}

	public void setAssignments(Set<Assignment> assignments) {
		this.assignments = assignments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<UserModule> getUserModules_1() {
		return this.userModules_1;
	}

	public void setUserModules_1(Set<UserModule> userModules_1) {
		this.userModules_1 = userModules_1;
	}

}
