package in.kmbs.vlethyme.entity;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SurveyQuestion generated by hbm2java
 */
@Entity
@Table(name = "survey_question", catalog = "vlethyme")
public class SurveyQuestion implements java.io.Serializable {

	private Integer id;
	private Survey survey;
	private String question;
	private Boolean type;
	private Set<SurveyOption> surveyOptions = new HashSet<SurveyOption>(0);
	private Set<SurveyAnswer> surveyAnswers = new HashSet<SurveyAnswer>(0);

	public SurveyQuestion() {
	}

	public SurveyQuestion(Survey survey) {
		this.survey = survey;
	}

	public SurveyQuestion(Survey survey, String question, Boolean type, Set<SurveyOption> surveyOptions, Set<SurveyAnswer> surveyAnswers) {
		this.survey = survey;
		this.question = question;
		this.type = type;
		this.surveyOptions = surveyOptions;
		this.surveyAnswers = surveyAnswers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "surveyId", nullable = false)
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@Column(name = "question", length = 65535)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "type")
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyQuestion")
	public Set<SurveyOption> getSurveyOptions() {
		return this.surveyOptions;
	}

	public void setSurveyOptions(Set<SurveyOption> surveyOptions) {
		this.surveyOptions = surveyOptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyQuestion")
	public Set<SurveyAnswer> getSurveyAnswers() {
		return this.surveyAnswers;
	}

	public void setSurveyAnswers(Set<SurveyAnswer> surveyAnswers) {
		this.surveyAnswers = surveyAnswers;
	}

}
