package in.kmbs.vlethyme.entity;

// Generated Mar 18, 2014 3:05:04 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "vlethyme")
public class User implements java.io.Serializable {

	private Integer id;
	private int roleId;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String username;
	private Set<MessgeRecepient> messgeRecepients = new HashSet<MessgeRecepient>(0);
	private Set<Forum> forums = new HashSet<Forum>(0);
	private Set<EventUser> eventUsers = new HashSet<EventUser>(0);
	private Set<UserCourse> userCourses = new HashSet<UserCourse>(0);
	private Set<GroupUser> groupUsers = new HashSet<GroupUser>(0);
	private Set<Group> groups = new HashSet<Group>(0);
	private Set<UserModule> userModules = new HashSet<UserModule>(0);
	private Set<SurveyUser> surveyUsers = new HashSet<SurveyUser>(0);
	private Set<SurveyAnswer> surveyAnswers = new HashSet<SurveyAnswer>(0);

	public User() {
	}

	public User(int roleId, String username) {
		this.roleId = roleId;
		this.username = username;
	}

	public User(int roleId, String firstName, String lastName, String email, String password, String username, Set<MessgeRecepient> messgeRecepients,
			Set<Forum> forums, Set<EventUser> eventUsers, Set<UserCourse> userCourses, Set<GroupUser> groupUsers, Set<Group> groups,
			Set<UserModule> userModules, Set<SurveyUser> surveyUsers, Set<SurveyAnswer> surveyAnswers) {
		this.roleId = roleId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.username = username;
		this.messgeRecepients = messgeRecepients;
		this.forums = forums;
		this.eventUsers = eventUsers;
		this.userCourses = userCourses;
		this.groupUsers = groupUsers;
		this.groups = groups;
		this.userModules = userModules;
		this.surveyUsers = surveyUsers;
		this.surveyAnswers = surveyAnswers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "roleId", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<MessgeRecepient> getMessgeRecepients() {
		return this.messgeRecepients;
	}

	public void setMessgeRecepients(Set<MessgeRecepient> messgeRecepients) {
		this.messgeRecepients = messgeRecepients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Forum> getForums() {
		return this.forums;
	}

	public void setForums(Set<Forum> forums) {
		this.forums = forums;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<EventUser> getEventUsers() {
		return this.eventUsers;
	}

	public void setEventUsers(Set<EventUser> eventUsers) {
		this.eventUsers = eventUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserCourse> getUserCourses() {
		return this.userCourses;
	}

	public void setUserCourses(Set<UserCourse> userCourses) {
		this.userCourses = userCourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<GroupUser> getGroupUsers() {
		return this.groupUsers;
	}

	public void setGroupUsers(Set<GroupUser> groupUsers) {
		this.groupUsers = groupUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserModule> getUserModules() {
		return this.userModules;
	}

	public void setUserModules(Set<UserModule> userModules) {
		this.userModules = userModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<SurveyUser> getSurveyUsers() {
		return this.surveyUsers;
	}

	public void setSurveyUsers(Set<SurveyUser> surveyUsers) {
		this.surveyUsers = surveyUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<SurveyAnswer> getSurveyAnswers() {
		return this.surveyAnswers;
	}

	public void setSurveyAnswers(Set<SurveyAnswer> surveyAnswers) {
		this.surveyAnswers = surveyAnswers;
	}

}
